name: Terraform AWS CI CD Pipeline Deployment
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    name: Terraform-AWS-CI-CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Display environment variables
        run: env
      
      - name: List directory contents
        run: ls -la ./terra-vpc
      
      - name: Display Terraform version
        run: terraform version
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./terra-vpc
      
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terra-vpc
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -input=false -no-color
        working-directory: ./terra-vpc
      
      - name: Show Terraform Plan output
        run: cat tfplan
        working-directory: ./terra-vpc
        if: always()
      
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terra-vpc
        if: ${{ github.ref == 'refs/heads/main' }}
      
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ./terra-vpc
        if: ${{ github.event.inputs.destroy == 'true' }}
