name: Terraform AWS CI CD Pipeline Deployment
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  build-infra:
    name: Terraform-AWS-CI-CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ env.AWS_REGION }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: ./terra-vpc

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terra-vpc

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan
        working-directory: ./terra-vpc
        continue-on-error: true

      - name: Debug Terraform Plan
        if: failure()
        run: |
          echo "Terraform Plan failed"
          cat ./terra-vpc/terraform.tfstate
        working-directory: ./terra-vpc

      - name: Terraform Apply
        if: success()
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./terra-vpc

      - name: Terraform Destroy
        if: success()
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ./terra-vpc
