name: Terraform AWS CI CD Pipeline Destroy
run-name: ${{ github.actor }} has triggered the destroy pipeline

on:
  workflow_dispatch: # This allows manual triggering from the GitHub Actions UI

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  destroy-infra:
    name: Terraform-AWS-CI-CD-Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Display environment variables
        run: env
      
      - name: List directory contents
        run: ls -la ./terra-vpc
      
      - name: Display Terraform version
        run: terraform version
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./terra-vpc
      
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ./terra-vpc
